#!/usr/bin/env python3
"""Hydrology pilot pipeline (DOMAIN_EXPANSION_ROADMAP.md Paket B3b).

Runs entirely against SYNTHETIC data generated by the EXACT same
(already-fixed) `dynamics.linear_reservoirs` functions this pilot itself
calls -- no network access needed. A real run against 6 CAMELS-DE
catchments (CC-BY-4.0, selected via `data/camels_de_adapter.py`) WAS
performed during development and is reported in docs/hydrology_pilot.md,
with small derived CSV excerpts committed to `data/camels_de/` under the
existing real-data-manifest convention.

Checks:

  1. Exact recovery: data generated by a KNOWN one-reservoir process (c,k)
     is recovered by the one-reservoir fit to a useful precision, and the
     resulting held-out MAE is near-exact (not merely "small").
  2. The two-reservoir fit does not do WORSE than one-reservoir on
     one-reservoir-generated data (it can degenerate towards k1~=k2, which
     is fine -- checked as a non-degradation property, not exact equality).
  3. Temporal split leakage guard: changing TEST-period values does not
     alter TRAIN-period fits (fit_1res/fit_2res unaffected).
  4. Missing-day robustness: an isolated single-day gap in the discharge
     series must not poison the WHOLE persistence-baseline MAE into NaN
     (each baseline's n_scored count is reported explicitly).
  5. ScopeViolationError guards (non-overlapping-but-ordered years,
     non-positive area, insufficient coverage).
  6. SCF_INTEGRATED_EXTENSION_IMPLEMENTATION_PLAN.md Paket C0 finding A:
     the persistence baseline's first test-day prediction must be the
     actual prior day's discharge, never a self-referential match to its
     own target value.
  7. SCF_INTEGRATED_EXTENSION_IMPLEMENTATION_PLAN.md Paket C0 finding B:
     the reservoir state must be propagated through the FULL calendar
     span, including any gap years strictly between training and test,
     never silently skipped via a train-union-test construction.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from scoped_correspondence.errors import ScopeViolationError  # noqa: E402
from scoped_correspondence.dynamics.linear_reservoirs import parallel_reservoir_step, parallel_reservoir_interval_discharge  # noqa: E402
from scoped_correspondence.validation.hydrology_pilot import (  # noqa: E402
    discharge_m3s_to_mm_day, run_catchment_hydro_pilot,
)


def require(cond: bool, msg: str) -> None:
    if not cond:
        raise AssertionError(msg)


def _make_dates(n: int, start_year: int = 1991) -> list:
    dates = []
    year, month, day = start_year, 1, 1
    days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    for _ in range(n):
        dates.append(f"{year:04d}-{month:02d}-{day:02d}")
        day += 1
        dim = days_in_month[month - 1] + (1 if month == 2 and year % 4 == 0 else 0)
        if day > dim:
            day = 1
            month += 1
            if month > 12:
                month = 1
                year += 1
    return dates


def _simulate_1res_synthetic(P: np.ndarray, c: float, k: float) -> np.ndarray:
    n = len(P)
    S = 0.0
    q = np.empty(n)
    for t in range(n):
        u = c * P[t]
        q[t] = parallel_reservoir_interval_discharge([S], u, [1.0], [k], 1.0)
        S = parallel_reservoir_step([S], u, [1.0], [k], 1.0)[0]
    return q


def check_exact_1res_recovery():
    rng = np.random.default_rng(20260924)
    n = 365 * 4
    dates = _make_dates(n)
    P = rng.gamma(1.0, 2.0, n)
    c_true, k_true = 0.4, 0.05
    Q_mm = _simulate_1res_synthetic(P, c_true, k_true)
    area = 100.0
    Q_m3s = Q_mm * area / 86.4

    r = run_catchment_hydro_pilot("SYN", dates, P, Q_m3s, area, (1991, 1992), (1993, 1994))
    require(abs(r.fit_1res["c"] - c_true) < 0.01, f"c recovery: got {r.fit_1res['c']}, want {c_true}")
    require(abs(r.fit_1res["k"] - k_true) < 0.005, f"k recovery: got {r.fit_1res['k']}, want {k_true}")
    require(r.mae_test["one_reservoir"] < 1e-2,
            f"one-reservoir MAE should be near-exact on one-reservoir-generated data; got {r.mae_test['one_reservoir']}")
    return r.to_dict()


def check_two_reservoir_does_not_degrade():
    rng = np.random.default_rng(1)
    n = 365 * 4
    dates = _make_dates(n)
    P = rng.gamma(1.0, 2.0, n)
    Q_mm = _simulate_1res_synthetic(P, 0.4, 0.05)
    area = 100.0
    Q_m3s = Q_mm * area / 86.4
    r = run_catchment_hydro_pilot("SYN2", dates, P, Q_m3s, area, (1991, 1992), (1993, 1994))
    require(r.mae_test["two_reservoir"] <= r.mae_test["one_reservoir"] + 1e-3,
            f"two-reservoir should not do meaningfully worse than one-reservoir here; "
            f"got 2res={r.mae_test['two_reservoir']}, 1res={r.mae_test['one_reservoir']}")
    return {"mae_1res": r.mae_test["one_reservoir"], "mae_2res": r.mae_test["two_reservoir"]}


def check_leakage_guard():
    rng = np.random.default_rng(2)
    n = 365 * 4
    dates = _make_dates(n)
    P = rng.gamma(1.0, 2.0, n)
    Q_mm = _simulate_1res_synthetic(P, 0.35, 0.08)
    area = 50.0
    Q_m3s = Q_mm * area / 86.4

    r_before = run_catchment_hydro_pilot("SYN3", dates, P, Q_m3s, area, (1991, 1992), (1993, 1994))

    years = np.array([int(d[:4]) for d in dates])
    Q_m3s_modified = Q_m3s.copy()
    Q_m3s_modified[years >= 1995] = 999.0  # drastically change only the TEST period

    r_after = run_catchment_hydro_pilot("SYN3", dates, P, Q_m3s_modified, area, (1991, 1992), (1993, 1994))
    require(r_before.fit_1res == r_after.fit_1res, "1-reservoir fit must be unaffected by test-period changes")
    require(r_before.fit_2res == r_after.fit_2res, "2-reservoir fit must be unaffected by test-period changes")
    return {"fit_1res": r_before.fit_1res}


def check_missing_day_robustness():
    rng = np.random.default_rng(3)
    n = 365 * 4
    dates = _make_dates(n)
    P = rng.gamma(1.0, 2.0, n)
    Q_mm = _simulate_1res_synthetic(P, 0.4, 0.05)
    area = 100.0
    Q_m3s = Q_mm * area / 86.4

    years = np.array([int(d[:4]) for d in dates])
    test_idx = np.where(years == 1993)[0]
    Q_m3s_gap = Q_m3s.copy()
    gap_day = test_idx[10]
    Q_m3s_gap[gap_day - 1] = np.nan  # knock out the day BEFORE a valid target day: poisons naive persistence only

    r = run_catchment_hydro_pilot("SYN4", dates, P, Q_m3s_gap, area, (1991, 1992), (1993, 1994))
    require(np.isfinite(r.mae_test["persistence"]), f"persistence MAE must not be NaN from one isolated gap; got {r.mae_test['persistence']}")
    require(r.n_scored["persistence"] == r.n_test_days - 1,
            f"persistence should be scored on exactly one fewer day than the other baselines; "
            f"got n_scored={r.n_scored}, n_test_days={r.n_test_days}")
    require(r.n_scored["seasonal"] == r.n_test_days, "seasonal/reservoir baselines unaffected by this gap")
    return {"n_scored": r.n_scored, "n_test_days": r.n_test_days}


def check_scope_violation_guards():
    n = 3650
    dates = _make_dates(n)
    rng = np.random.default_rng(4)
    P = rng.gamma(1.0, 2.0, n)
    Q_m3s = np.abs(rng.normal(1.0, 0.3, n))
    try:
        run_catchment_hydro_pilot("X", dates, P, Q_m3s, -5.0, (1991, 1992), (1993, 1994))
        raise AssertionError("should reject non-positive area")
    except ScopeViolationError:
        pass
    try:
        run_catchment_hydro_pilot("X", dates, P, Q_m3s, 10.0, (1991, 1994), (1993, 1995))
        raise AssertionError("should reject overlapping train/test years")
    except ScopeViolationError:
        pass
    try:
        run_catchment_hydro_pilot("X", dates[:50], P[:50], Q_m3s[:50], 10.0, (1991, 1991), (1991, 1991))
        raise AssertionError("should reject insufficient coverage")
    except ScopeViolationError:
        pass
    try:
        discharge_m3s_to_mm_day(Q_m3s, 0.0)
        raise AssertionError("should reject zero area in unit conversion")
    except ScopeViolationError:
        pass
    return {"checked": 4}


def check_c0_finding_a_persistence_not_self_referential():
    """SCF_INTEGRATED_EXTENSION_IMPLEMENTATION_PLAN.md Paket C0, finding A: the
    persistence baseline's first test-day prediction must be the actual PRIOR day's
    discharge, never that same day's own target value.

    Construction (detects the bug via the AGGREGATE MAE alone, with no need to
    inspect internal per-day arrays): discharge is constant EXCEPT for a single
    anomalous day -- the very last training day, immediately preceding the first
    test day. Every other test day has perfect persistence (constant series, zero
    error). A SELF-referential first-day prediction (the old bug) would score that
    day as a free zero-error match too, giving an overall persistence MAE of
    EXACTLY 0. The correct prediction uses the actual (very different) prior day,
    giving a known nonzero first-day error and thus a calculable positive MAE.
    """
    n = 365 + 366  # 1991 (365 days) + 1992 (leap, 366 days), contiguous, no gap needed for this finding
    dates = _make_dates(n)
    years = np.array([int(d[:4]) for d in dates])
    rng = np.random.default_rng(5)
    P = rng.gamma(1.0, 2.0, n)

    area = 86.4  # makes discharge_m3s_to_mm_day the identity: q_mm_day = 86.4*q_m3s/86.4 = q_m3s
    normal_value, anomaly_value = 5.0, 50.0
    Q_m3s = np.full(n, normal_value)
    last_train_idx = int(np.where(years == 1991)[0][-1])
    Q_m3s[last_train_idx] = anomaly_value  # last training day only; every test day stays "normal_value"

    r = run_catchment_hydro_pilot("SYNA", dates, P, Q_m3s, area, (1991, 1991), (1992, 1992))
    n_test = r.n_test_days
    want_mae = abs(anomaly_value - normal_value) / n_test  # only the first test day contributes error
    require(abs(r.mae_test["persistence"] - want_mae) < 1e-9,
            f"persistence MAE should reflect the real prior-day anomaly ({want_mae}), "
            f"not a self-referential free match (which would give exactly 0.0); got {r.mae_test['persistence']}")
    require(r.mae_test["persistence"] > 1e-6, "sanity: must not be the old bug's exact-zero result")
    return {"mae_persistence": r.mae_test["persistence"], "want": want_mae, "n_test_days": n_test}


def check_c0_finding_b_gap_years_propagated():
    """SCF_INTEGRATED_EXTENSION_IMPLEMENTATION_PLAN.md Paket C0, finding B: the
    reservoir state must be propagated through the FULL calendar span, including
    years strictly between training and test (never a train-union-test skip that
    silently jumps the state across the gap with zero elapsed simulated time).

    Exact one-reservoir generating process with a REAL multi-year gap between
    training and test: since the true (c,k) are used directly (no fitting noise),
    correct gap propagation must reproduce the test period to near machine
    precision; the old union-only construction would show a real, measurable
    error instead (independently confirmed during development: MAE ~1.1e-3 old
    vs 0.0 new on this exact construction).
    """
    n = 365 * 6  # 1991-1996: 2 years train, 2 years gap, 2 years test
    dates = _make_dates(n)
    rng = np.random.default_rng(6)
    P = rng.gamma(1.0, 2.0, n)
    c_true, k_true = 0.4, 0.01  # slow reservoir: gap-skipping causes a large, easily-detected error
    Q_mm = _simulate_1res_synthetic(P, c_true, k_true)
    area = 100.0
    Q_m3s = Q_mm * area / 86.4

    r = run_catchment_hydro_pilot("SYNB", dates, P, Q_m3s, area, (1991, 1992), (1995, 1996))
    # Independent reference: integrate the SAME known (c,k) continuously over the
    # FULL span via the module's own (already-verified) simulator called directly
    # on the full contiguous array -- this is the definition of "correct", checked
    # against the pilot's actual output for the test period specifically.
    years = np.array([int(d[:4]) for d in dates])
    full_mask = (years >= 1991) & (years <= 1996)
    test_mask = (years >= 1995) & (years <= 1996)
    ref_full = _simulate_1res_synthetic(P[full_mask], c_true, k_true)
    ref_test = ref_full[test_mask[full_mask]]
    true_test = Q_mm[test_mask]
    require(np.mean(np.abs(ref_test - true_test)) < 1e-9, "sanity: reference construction itself must be exact")

    # The pilot FITS (c,k) rather than using the true values, so allow a small fit-noise
    # tolerance -- but this must be orders of magnitude tighter than the ~1e-3 error a
    # gap-skipping bug would introduce.
    require(r.mae_test["one_reservoir"] < 1e-4,
            f"one-reservoir MAE should be near-exact when the gap is correctly propagated; "
            f"got {r.mae_test['one_reservoir']} (a gap-skipping bug would give ~1e-3 or worse here)")
    return {"mae_1res": r.mae_test["one_reservoir"], "fit_1res": r.fit_1res}


CHECKS = [
    ("exact_1res_recovery", check_exact_1res_recovery),
    ("two_reservoir_does_not_degrade", check_two_reservoir_does_not_degrade),
    ("leakage_guard", check_leakage_guard),
    ("missing_day_robustness", check_missing_day_robustness),
    ("scope_violation_guards", check_scope_violation_guards),
    ("c0_finding_a_persistence_not_self_referential", check_c0_finding_a_persistence_not_self_referential),
    ("c0_finding_b_gap_years_propagated", check_c0_finding_b_gap_years_propagated),
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json-out", type=Path, default=Path(__file__).with_name("verify_hydrology_pilot_results.json"))
    args = parser.parse_args()

    report = {
        "package": "DOMAIN_EXPANSION_ROADMAP.md Paket B3b (hydrology pilot, synthetic-only CI check)",
        "timestamp": dt.datetime.now().astimezone().isoformat(timespec="seconds"),
        "python": sys.version.split()[0],
        "checks": {},
    }

    all_ok = True
    for name, fn in CHECKS:
        try:
            detail = fn()
            report["checks"][name] = {"status": "pass", "detail": detail}
            print(f"PASS  {name}")
        except AssertionError as e:
            all_ok = False
            report["checks"][name] = {"status": "fail", "error": str(e)}
            print(f"FAIL  {name}: {e}")
        except Exception as e:  # noqa: BLE001
            all_ok = False
            report["checks"][name] = {"status": "error", "error": f"{type(e).__name__}: {e}"}
            print(f"ERROR {name}: {type(e).__name__}: {e}")

    args.json_out.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
    print(f"\n{sum(1 for c in report['checks'].values() if c['status'] == 'pass')}/{len(CHECKS)} checks passed")
    print(f"Report written to {args.json_out}")
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
